parameters:
- name: rust
  displayName: Rust Version
  type: string
  # a version that builds with the old asm style
  # az pipelines run --name cokesme.applepie --parameters rust=nightly-2019-07-21
  default: 'nightly-2019-07-21'

trigger:
- master
- releases/*

pr:
- master
- releases/*

jobs:
- job: Bochservisor
  displayName: "Bochservisor build test"
  pool:
    vmImage: 'windows-latest'
  variables:
      RUSTUP_TOOLCHAIN: ${{ parameters.rust }} 
  steps:
  - script: |
      mkdir "$(Build.ArtifactStagingDirectory)/bochservisor"
    displayName: Prep Build
  - script: |
      cargo build --manifest-path bochservisor/Cargo.toml --release
    displayName: Build 
  - task: CopyFiles@2
    inputs:
      sourceFolder: bochservisor 
      targetFolder: $(Build.ArtifactStagingDirectory)/bochservisor
  - publish: $(Build.ArtifactStagingDirectory)
    artifact: bochservisor-x64-win

- job: Bochs
  displayName: "Full bochs build" 
  pool:
    vmImage: 'windows-latest'
  steps:
  - pwsh: |
      curl.exe -L -o ubuntu-2004.appx https://aka.ms/wslubuntu2004
      copy-item ubuntu-2004.appx ubuntu.zip
      expand-archive ubuntu.zip
      cd ubuntu
      copy-item Ubuntu_2004.2021.825.0_x64.appx ubuntu.zip
      expand-archive ubuntu.zip
      ubuntu\ubuntu.exe install --root
  # the build tools script does need to be run even on the msft hosted machines
  - script: |
      C:\\Windows\\System32\\bash.exe -c "sudo apt update -q -y&&sudo apt install -y make"
      call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      python build.py
    displayName: Build 
  - publish: bochs_build/bochs.exe
    artifact: bochs-x64-win