parameters:
- name: rust
  displayName: Rust Version
  type: string
- name: old
  displayName: Old asm?
  type: boolean
  default: true

trigger:
- master
- releases/*

pr:
- master
- releases/*

jobs:
- job: Windows
  pool:
    vmImage: 'windows-latest'
  variables:
	- ${{ if eq(parameters.old, true) }}:
      RUSTUP_TOOLCHAIN: 'nightly-2021-11-10'
  steps:
  - script: |
      mkdir "$(Build.ArtifactStagingDirectory)/bochservisor"
    displayName: Prep Build
  - script: |
      cargo build --manifest-path bochservisor/Cargo.toml --release
    displayName: Build 
  - task: CopyFiles@2
    inputs:
      sourceFolder: bochservisor 
      targetFolder: $(Build.ArtifactStagingDirectory)\bochservisor
  - publish: $(Build.ArtifactStagingDirectory)
    artifact: bochservisor-x64-win
